### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by upperhill** [inconshreveable/srvdir#11]
go version go1.2.1 linux/amd64

make
```
go fmt srvdir/...
go get -tags 'debug' -d -v srvdir/...
go install -gcflags "-N -l" -tags 'debug' srvdir/cmd/srvdir
go install -gcflags "-N -l" -tags 'debug' srvdir/cmd/srvdird
# srvdir/server
src/srvdir/server/metrics.go:21: unknown keen.Client field 'ApiKey' in struct literal
src/srvdir/server/metrics.go:21: unknown keen.Client field 'ProjectToken' in struct literal
make: *** [server] Error 2
```

**Comment by inconshreveable** [comment]
Yes indeed, this should be updated to `WriteKey` and `ProjectId`

**Comment by upperhill** [comment]
OK,  the new line is 
```
client := &keen.Client{WriteKey: keenApiKey, ProjectId: keenProjectToken}
```

i get a new error

```
make
go fmt srvdir/...
go get -tags 'debug' -d -v srvdir/...
go install -gcflags "-N -l" -tags 'debug' srvdir/cmd/srvdir
# gopkg.in/yaml.v1
src/gopkg.in/yaml.v1/encode.go:188: undefined: strings.IndexByte
make: *** [client] Error 2

```

**Comment by inconshreveable** [comment]
yeah, you'll need to compile with Go 1.3+

**Comment by upperhill** [comment]
I managed to install golang  1.3.1 on ubuntu 12.04 and 14.04.

```
sudo apt-get install python-software-properties
sudo add-apt-repository ppa:lvillani/go
sudo apt-get update
sudo apt-get install golang -y
```

now i get this error msg.

```
make
go fmt srvdir/...
go get -tags 'debug' -d -v srvdir/...
go install -gcflags "-N -l" -tags 'debug' srvdir/cmd/srvdir
go install -gcflags "-N -l" -tags 'debug' srvdir/cmd/srvdird
# srvdir/server
src/srvdir/server/metrics.go:21: unknown keen.Client field 'ProjectId' in struct literal
make: *** [server] Error 2
```

**Comment by inconshreveable** [comment]
Ah, looks like it should be `ProjectID`: https://github.com/inconshreveable/go-keen#writing-events

**Comment by upperhill** [comment]
Thank you!

**Comment by upperhill** [comment]
How do I compile with certificate? I'm only using tls.

**Comment by upperhill** [comment]
[07/10/15 19:41:10] [INFO] [server] [[::]:4443] Listening for tunnel sessions on [::]:4443
[07/10/15 19:41:14] [INFO] [server] [[::]:4443] New tunnel session from: XX.XX.XXX.XX:40674
[07/10/15 19:41:14] [EROR] [session] Failed to accept auth stream: Session closed
[07/10/15 19:41:14] [INFO] [session] Session mux shutdown with code 2 error remote error: bad certificate debug []

**Comment by inconshreveable** [comment]
You'll need to replace the root CA with your own. Here's my favorite guide to doing that with openssl: http://datacenteroverlords.com/2012/03/01/creating-your-own-ssl-certificate-authority/
